services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.3
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080

  postgres:
    container_name: postgres
    image: postgres:16
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres.ibyziayfhbxjbvrmemhj
      - POSTGRES_PASSWORD=Semhaeyldm777$
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  evolution_instances:
  evolution_store:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge